//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public int Id { get; set; }
        public int FactoryId { get; set; }
        public int CategoryId { get; set; }
        public int Number { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Factory Factory { get; set; }
        public virtual Category Category { get; set; }
    }
}
